### ISSUE TITLE
Don't let users delegate the vote to themselves

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/decidim-module-action_delegator#12]
As part of https://github.com/coopdevs/decidim-coopcat/issues/3, when creating a delegation we shouldn't allow granter and grantee be the same user.

When that happens we need to let the user know the reason with a specific error for the form field. This is done serverside populating the object errors using a Rectify's form object per Decidim's convention and the `form-error` CSS class.

See below :point_down: 

![Screenshot from 2020-09-07 18-14-10](https://user-images.githubusercontent.com/762088/92405493-fa1d3400-f135-11ea-8947-9560a77a6b3b.png)

**Comment by microstudi** [comment]
We probably will need to use the method `decidim_form_for` instead of `form_for` in the views.
