### ISSUE TITLE
Check :index :delegation permission to render menu item

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/decidim-module-action_delegator#13]
For unknown reasons, we couldn't use `allowed_to? :index, :delegation` when rendering the `User delegations` menu item and had to revert it in https://github.com/coopdevs/decidim-module-action_delegator/pull/11/commits/a197b20a1b0d731510c3d75ec6f87f55ec8a6f62. We need to make the proper permission work.

**Comment by microstudi** [comment]
This is because permissions aren't registered until we hit the AdminController in our module, we need to investigate the best way to hack that.
