### ISSUE TITLE
Potential collaboration

### ISSUE THREAD

**Issue by oliverbarnes** [coopdevs/decidim-module-action_delegator#16]
Hello Coopdev team and @microstudi,

We're working on a [delegations (and voting) api](https://liquidvoting.io/), which we're currently spiking an integration with Decidim.

At a call with @carolromero and @andreslucena yesterday they mentioned your project, and after I joined Decidim devs' Telegram, Ivan suggested we contact you here on the repo.

We've spent a few hours familiarizing with the project, and are curious to hear more. We'd also like to tell you where we're at, so perhaps we can find ways to collaborate :) 

Would you be up for a Jitsi call tomorrow afternoon? Or another day that works, of course.

**Comment by sauloperez** [comment]
Hi @oliverbarnes ! We'll be glad to chat about it. I'll contact you through email to set up a date.

**Comment by oliverbarnes** [comment]
Hey @sauloperez, sounds good! Looking forward to it, have a great weekend
