### ISSUE TITLE
Delegations after upgade 0.27

### ISSUE THREAD

**Issue by nuria-alonso** [coopdevs/decidim-module-action_delegator#168]
To reproduce: 

1. Go to demo.cercles.coop
2. Create one consultation 
3. Create a New Configuration on Governaça Societària
4. Create a census with email 
5. Make a delegation for one user to another
6. Try to vote (you can't make more than one action vote, you must refresh)
7. See video
[Enregistrament de pantalla des de 6-2-24 11:43:55.webm](https://github.com/coopdevs/decidim-module-action_delegator/assets/40388743/fa7b46cd-0848-4452-9ea8-09da3de8f0ab)
 
Report Núria ->

We have configured the query question with the permission "Action delegator".
![Captura de pantalla de 2024-01-26 12-14-54](https://github.com/coopdevs/decidim-module-action_delegator/assets/14790901/dc72de4b-6884-4246-9e0d-069548c392cb)
![Captura de pantalla de 2024-01-26 12-33-32](https://github.com/coopdevs/decidim-module-action_delegator/assets/14790901/ad33e74f-1d64-4613-8ec0-643b4987ef91)

We have prepared the census linked to the process, with various delegations.
![Captura de pantalla de 2024-01-26 12-15-37](https://github.com/coopdevs/decidim-module-action_delegator/assets/14790901/70ba21a5-9806-4720-9965-e8750eae2c57)
![Captura de pantalla de 2024-01-26 12-16-16](https://github.com/coopdevs/decidim-module-action_delegator/assets/14790901/78d84f9e-b7a6-4012-bbb3-eab5eb6334e7)

At the time of casting the vote, the link to delegate the vote does not appear.
![Captura de pantalla de 2024-01-26 12-16-31](https://github.com/coopdevs/decidim-module-action_delegator/assets/14790901/07d391a4-ccf9-4070-85e6-737d3e61e33a)
![Captura de pantalla de 2024-01-26 12-16-41](https://github.com/coopdevs/decidim-module-action_delegator/assets/14790901/de94441e-5067-446c-ad26-a1eb8a542eb5)

By submitting the vote, only the direct vote is registered.

**Comment by microstudi** [comment]
The fix #169 is deployed at  demo.cercles.coop
