### ISSUE TITLE
Execute consultations migrations by default

### ISSUE THREAD

**Issue by microstudi** [coopdevs/decidim-module-action_delegator#25]
As this module depends on consultations and consultations is not installed by default, maybe we should apply automatically its migrations when executing this. Otherwise, installing this module without installing consultations before will result in an error not documented here.

```
bundle exec rails decidim_consultations:install:migrations
```
https://github.com/decidim/decidim/tree/develop/decidim-consultations

**Comment by mllocs** [comment]
@microstudi is this issue only about updating the Readme or there's a way to automatically to that?

**Comment by microstudi** [comment]
> @microstudi is this issue only about updating the Readme or there's a way to automatically to that?

I think we can easily automate that. Just call the rake task before running our own migration
