### ISSUE TITLE
Don't allow duplicating delegations

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/decidim-module-action_delegator#26]
It is possible to create two exact delegations from admin which results in duplicate vote buttons. Delegations must have a unique (granter_id, consultation_id) pair so that a member can only have a vote in a consultation (although that can't happen by pure chance and due to other reasons).

Nothing stops you in the admin's delegation form view to end up with :point_down: 
![Screenshot from 2020-09-23 09-13-08](https://user-images.githubusercontent.com/762088/93979241-5eb6d080-fd7d-11ea-98e2-a2f782dbd571.png)

and then :point_down: 

![Screenshot from 2020-09-23 09-18-33](https://user-images.githubusercontent.com/762088/93979558-c705b200-fd7d-11ea-94f8-2482f5127154.png)

**Comment by mllocs** [comment]
@sauloperez @microstudi  I'm thinking between adding a custom validation to the Delegation model or doing the validation in the CreateDelegation command. Thoughts?

**Comment by sauloperez** [comment]
It feels to me this belongs to the model as it's something. It's something we don't want our data model to support that's why I'd like to have the DB enforce it too. A compound (granter, grantee) unique index should suffice.

**Comment by mllocs** [comment]
@sauloperez shouldn't this also be scoped by setting?

**Comment by sauloperez** [comment]
oh, yes, right!
