### ISSUE TITLE
/authorizations can't find `root_path` for delegations_verifier

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/decidim-module-action_delegator#46]
When visiting `/authorizations` from your account page, in `decidim-verifications/app/views/decidim/verifications/authorizations/index.html.erb`, Decidim check's the auth method `root_path` and fails with `delegations_verifier`.

That's because in https://github.com/decidim/decidim/blob/7abeb1e08cd1abbdb06fd3fca6bc2dc8df594842/decidim-verifications/lib/decidim/verifications/adapter.rb#L107-L109, the `manifest.name` doesn't match the actual engine name.

However, we still have no user-facing logic implement for our verification. That `root_path` points to them.

**Comment by mllocs** [comment]
I stumbled upon this issue today, and I need to fix it, the sms verification kind of depends on the `/authorizations` page.

**Comment by sauloperez** [comment]
Yes, I just did too while QAing your PR. If you want to get going this is the nasty hack I added to unblock it.

```ruby
<% next if unauthorized_method.name == "delegations_verifier" %>
```
at decidim-verifications/app/views/decidim/verifications/authorizations/index.html.erb:49
