### ISSUE TITLE
Show delegates votes in results view.

### ISSUE THREAD

**Issue by LauraJaimeC** [coopdevs/decidim-module-action_delegator#82]
The delegates votes don't show in results view. Only show the count of general votes.

It would be nice if you could show the delegated votes in the view as it is done in the image.

![results_view](https://user-images.githubusercontent.com/75725233/101886889-6deb3480-3b9c-11eb-8a83-ea49d7e27a15.png)

For example:

2 vots / 4 vots delegats / 9 participants

and the same in totals.

Thanks! :heart:

**Comment by tramuntanal** [comment]
We've started the work for this in https://github.com/CodiTramuntana/decidim-module-action_delegator/pull/1.
@microstudi @sauloperez would you like us to PR to your repo?

cc/ @LauraJaimeC

**Comment by sauloperez** [comment]
Thanks! we greatly appreciate this contribution!

**Comment by microstudi** [comment]
We'll be thrilled @tramuntanal :smile: !

**Comment by sauloperez** [comment]
Solved by #83
